document.writeln("<!--导航栏 -->");
document.writeln("<div id=\'navigation_bar\'>");
document.writeln("    <nav class=\'navbar navbar-expand-lg navbar-dark bg-dark fixed-top \'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <a class=\'navbar-brand\' href=\'index.html\'>HHHSL</a>");
document.writeln("        <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarSupportedContent\'");
document.writeln("          aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("          <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("          <ul class=\'navbar-nav me-auto mb-2 mb-lg-0\'>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("              <a class=\'nav-link active\' aria-current=\'page\' href=\'index.html\'>首页</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("              <a class=\'nav-link\' href=\'recommend.html\'>推荐</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("              <a class=\'nav-link\' href=\'daily.html\'>日常</a>");
document.writeln("            </li>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("              <a class=\'nav-link\' href=\'note.html\'>笔记</a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("          <ul class=\'navbar-nav mb-2 mb-lg-0 d-flex\'>");
document.writeln("            <li class=\'nav-item\'>");
document.writeln("              <a class=\'nav-link\' href=\'login.html\'>登录</a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("  </div>");